bind_addr = "8888"
log_level = "debug"
database_dns = "postgres://localhost/snippets?sslmode=disable&user=postgres&password=postgres"
test_database_dns = "postgres://localhost/snippets_test?sslmode=disable&user=postgres&password=postgres"
jwt_signing_key = "3eo2aslQWk32mAxaQwk3As"